ci:
    skip: [pylint-local]

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-ast

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile=black"]

-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter

-   repo: https://github.com/asottile/dead
    rev: v1.5.0
    hooks:
    -   id: dead

-   repo: local
    hooks:
    # Pylint is run as local hook to make use of the repo venv.
    -   id: pylint-local
        name: pylint-local
        entry: pylint
        language: system
        types: [ python ]
        require_serial: true

-   repo: https://github.com/PyCQA/pylint
    rev: v2.14.4
    hooks:
    # Pylint is also run from within pre-commit for CI purposes.
    -   id: pylint
        # Ignore imports when not running in a local env.
        args: ["--disable=E0401"]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        # Assert is used exclusively in pytest.
        args: ["--skip=B101"]
