# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

# Set build OS and python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install project dependencies so autodoc can generate properly.
python:
  install:
    - method: pip
      path: .
