
name: Tests

on:
  push:
    paths-ignore:
      - '**.md'  # Ignore documentation for tests
      - '.pre-commit-config.yaml'  # Stop pre-commit CI triggering tests.
  pull_request:
    paths-ignore:
      - '**.md'
      - '.pre-commit-config.yaml'

jobs:

  run-test:
    name: ${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        python-version:
          - "3.10"
          - "3.11"
        architecture:
          - x64

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          python -m pip install .

      - name: Run tests
        run: |
          python -m pytest tests/
